apiVersion: v1
kind: Service
metadata:
  name: customers-loadbalancer
  labels:
      app: customers
spec:
  selector:
    app: customers
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
    
