apiVersion: v1
kind: Pod
metadata:
  name: customers
  labels:
    app: customers
spec:
  containers:
    - name: customers
      image: hadilkortas/customers-service
      ports:
        - containerPort: 80
          name: demo-http