apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  containers:
    - name: api-gateway
      image: hadilkortas/api-gateway
      ports:
        - containerPort: 80
          name: demo-http