apiVersion: v1
kind: Service
metadata:
  name: api-gateway-loadbalancer
  labels:
      app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
    nodePort: 32047
  type: LoadBalancer
    
