apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  labels:
      app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
    nodePort: 32000
  type: NodePort
    