apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager:9093
    rule_files:
      - "prometheus-rules.yaml"
    scrape_configs:
      - job_name: 'api-gateway'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  name: prometheus-prometheus-0
  namespace: monitoring
