apiVersion: v1
kind: Service
metadata:
  name: api-gateway-charts-service
  labels:
    app:  api-gateway-charts
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api-gateway-charts