apiVersion: v1
kind: Pod
metadata:
  name: orders
  labels:
    app: orders
spec:
  containers:
    - name: orders
      image: hadilkortas/orders-service
      ports:
        - containerPort: 80
          name: demo-http