apiVersion: v1
kind: Service
metadata:
  name: orders-nodeport
  labels:
      app: orders
spec:
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: NodePort
    
