apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 5
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: hadilkortas/orders-service
        ports:
        - containerPort: 5002
