apiVersion: v1
kind: Pod
metadata:
  name: books
  labels:
    app: books
spec:
  containers:
    - name: books
      image: hadilkortas/books-service
      ports:
        - containerPort: 80
          name: demo-http