apiVersion: v1
kind: Service
metadata:
  name: books-nodeport
  labels:
      app: books
spec:
  selector:
    app: books
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
    
