apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-book-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: micro-book-app
  template:
    metadata:
      labels:
        app: micro-book-app
    spec:
      containers:
      - name: micro-book-app-container
        image: hadilkortas/books-service:latest
        ports:
        - containerPort: 80
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: micro-book-app-service
spec:
  selector:
    app: micro-book-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
